package com.iims.iims.news.entity;

public enum NewsCategory {
    INCUBATION_PROGRAM_NEWS,
    FUNDING_OPPORTUNITIES,
    STARTUP_SHOWCASE,
    UPCOMING_EVENTS,
    SUCCESS_STORIES,
    MENTOR_RESOURCES,
    INVESTOR_PITCH_SUMMARIES,
    MARKET_INSIGHTS,
    GENERAL_ANNOUNCEMENT,
    ALUMNI_HIGHLIGHTS
}